CREATE OR REPLACE FUNCTION add_user_vote(userID INT, photoID INT)
RETURNS BOOLEAN
AS $$
BEGIN
	INSERT INTO votes(userID, photoID, voteDate) VALUES ($1, $2, NOW());
		RETURN TRUE;
	EXCEPTION WHEN OTHERS THEN
		RETURN FALSE;
END
$$ LANGUAGE plpgsql;
